package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/hdmain/goincus/internal/secrets"
)

// Config holds all runtime settings for the goincus service.
type Config struct {
	Server   ServerConfig   `yaml:"server"`
	Auth     AuthConfig     `yaml:"auth"`
	Database DatabaseConfig `yaml:"database"`
	Redis    RedisConfig    `yaml:"redis"`
	Incus    IncusConfig    `yaml:"incus"`
	Ports    PortsConfig    `yaml:"ports"`
	Defaults DefaultsConfig `yaml:"defaults"`
}

type ServerConfig struct {
	Host         string   `yaml:"host"`
	Port         int      `yaml:"port"`
	ReadTimeout  Duration `yaml:"read_timeout"`
	WriteTimeout Duration `yaml:"write_timeout"`
	IdleTimeout  Duration `yaml:"idle_timeout"`
}

type AuthConfig struct {
	// APIKeys are accepted via Authorization: Bearer <key> or X-API-Key.
	APIKeys []string `yaml:"api_keys"`
}

type DatabaseConfig struct {
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	User     string `yaml:"user"`
	Password string `yaml:"password"`
	Name     string `yaml:"name"`
	SSLMode  string `yaml:"sslmode"`
	MaxConns int32  `yaml:"max_conns"`
	MinConns int32  `yaml:"min_conns"`
}

type RedisConfig struct {
	Host      string `yaml:"host"`
	Port      int    `yaml:"port"`
	Password  string `yaml:"password"`
	DB        int    `yaml:"db"`
	KeyPrefix string `yaml:"key_prefix"`
}

type IncusConfig struct {
	SocketPath    string   `yaml:"socket_path"`
	Project       string   `yaml:"project"`
	StoragePool   string   `yaml:"storage_pool"`
	Network       string   `yaml:"network"`
	ImageServer   string   `yaml:"image_server"`
	ImageProtocol string   `yaml:"image_protocol"`
	DefaultImage  string   `yaml:"default_image"`
	Profiles      []string `yaml:"profiles"`
}

type PortsConfig struct {
	HostRangeStart       int   `yaml:"host_range_start"`
	HostRangeEnd         int   `yaml:"host_range_end"`
	DefaultInternalPorts []int `yaml:"default_internal_ports"`
}

type DefaultsConfig struct {
	CPUCores  int `yaml:"cpu_cores"`
	MemoryMB  int `yaml:"memory_mb"`
	StorageGB int `yaml:"storage_gb"`
	Processes int `yaml:"processes"`
}

// Addr returns the HTTP listen address.
func (s ServerConfig) Addr() string {
	return fmt.Sprintf("%s:%d", s.Host, s.Port)
}

// DSN returns a PostgreSQL connection string.
func (d DatabaseConfig) DSN() string {
	return fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=%s",
		d.Host, d.Port, d.User, d.Password, d.Name, d.SSLMode,
	)
}

// Addr returns host:port for Redis.
func (r RedisConfig) Addr() string {
	return fmt.Sprintf("%s:%d", r.Host, r.Port)
}

// Load reads configuration from a YAML file.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}

	cfg := Default()
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}

// Save writes the config as YAML with restrictive permissions.
func Save(path string, cfg *Config) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir config dir: %w", err)
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	header := []byte("# Generated by goincus init — keep this file private.\n")
	if err := os.WriteFile(path, append(header, data...), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// Default returns sane defaults matching the goincus port contract.
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			Host:         "0.0.0.0",
			Port:         9603,
			ReadTimeout:  Duration(30 * time.Second),
			WriteTimeout: Duration(60 * time.Second),
			IdleTimeout:  Duration(120 * time.Second),
		},
		Auth: AuthConfig{
			APIKeys: nil,
		},
		Database: DatabaseConfig{
			Host:     "127.0.0.1",
			Port:     9601,
			User:     "goincus",
			Password: "",
			Name:     "goincus",
			SSLMode:  "disable",
			MaxConns: 25,
			MinConns: 2,
		},
		Redis: RedisConfig{
			Host:      "127.0.0.1",
			Port:      9602,
			Password:  "",
			DB:        0,
			KeyPrefix: "goincus:",
		},
		Incus: IncusConfig{
			SocketPath:    "",
			Project:       "default",
			StoragePool:   "default",
			Network:       "incusbr0",
			ImageServer:   "https://images.linuxcontainers.org",
			ImageProtocol: "simplestreams",
			DefaultImage:  "ubuntu/24.04",
			Profiles:      []string{"goincus-unprivileged"},
		},
		Ports: PortsConfig{
			HostRangeStart:       20000,
			HostRangeEnd:         29999,
			DefaultInternalPorts: []int{22, 80, 443},
		},
		Defaults: DefaultsConfig{
			CPUCores:  1,
			MemoryMB:  512,
			StorageGB: 10,
			Processes: 512,
		},
	}
}

// GenerateInitialized builds a default config with fresh passwords and API keys.
func GenerateInitialized() (*Config, error) {
	cfg := Default()

	dbPass, err := secrets.RandomPassword(24)
	if err != nil {
		return nil, err
	}
	redisPass, err := secrets.RandomPassword(24)
	if err != nil {
		return nil, err
	}
	apiKey, err := secrets.RandomAPIKey()
	if err != nil {
		return nil, err
	}
	adminKey, err := secrets.RandomAPIKey()
	if err != nil {
		return nil, err
	}

	cfg.Database.Password = dbPass
	cfg.Redis.Password = redisPass
	cfg.Auth.APIKeys = []string{apiKey, adminKey}
	return cfg, nil
}

// Validate checks required fields and port ranges.
func (c *Config) Validate() error {
	if c.Server.Port <= 0 || c.Server.Port > 65535 {
		return fmt.Errorf("invalid server port: %d", c.Server.Port)
	}
	if c.Database.Host == "" || c.Database.Port <= 0 {
		return fmt.Errorf("database host/port required")
	}
	if c.Redis.Host == "" || c.Redis.Port <= 0 {
		return fmt.Errorf("redis host/port required")
	}
	if c.Ports.HostRangeStart >= c.Ports.HostRangeEnd {
		return fmt.Errorf("invalid host port range: %d-%d", c.Ports.HostRangeStart, c.Ports.HostRangeEnd)
	}
	if c.Defaults.CPUCores < 1 {
		return fmt.Errorf("defaults.cpu_cores must be >= 1")
	}
	if c.Defaults.MemoryMB < 64 {
		return fmt.Errorf("defaults.memory_mb must be >= 64")
	}
	if c.Defaults.StorageGB < 1 {
		return fmt.Errorf("defaults.storage_gb must be >= 1")
	}
	if len(c.Auth.APIKeys) == 0 {
		return fmt.Errorf("auth.api_keys must contain at least one key (run: goincus init)")
	}
	for _, key := range c.Auth.APIKeys {
		if strings.Contains(key, "REPLACE_WITH") {
			return fmt.Errorf("%s looks like a package template — run: sudo goincus init (do not overwrite an existing working config unless secrets were lost)", setupHintPath())
		}
	}
	if strings.Contains(c.Database.Password, "REPLACE_WITH") || strings.Contains(c.Redis.Password, "REPLACE_WITH") {
		return fmt.Errorf("%s has template passwords — apt upgrade used to overwrite this file; restore a backup or run: sudo goincus init --force", setupHintPath())
	}
	return nil
}

func setupHintPath() string {
	return "/etc/goincus/config.yaml"
}

// ValidAPIKey reports whether key is configured.
func (c *Config) ValidAPIKey(key string) bool {
	if key == "" {
		return false
	}
	for _, k := range c.Auth.APIKeys {
		if k != "" && k == key {
			return true
		}
	}
	return false
}
